apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment  # Nome do deployment
  labels:
    app: frontend            # Rótulo de identificação
spec:
  replicas: 2                # Número de réplicas/pods
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gabrielaschubert/frontend:latest  # Imagem do seu DockerHub
          ports:
            - containerPort: 80
