# Define a versão da API do Kustomize usada
apiVersion: kustomize.config.k8s.io/v1beta1

# Define o tipo deste arquivo como Kustomization
kind: Kustomization

# Inclui os recursos Kubernetes (deployment e service)
resources:
- deployment.yaml
- service.yaml

# Substitui as imagens no deployment.yaml por uma nova versão da imagem
  # Atualiza a imagem chamada "frontend" para usar a imagem do Docker Hub com novo tag

  # Garante também que "gabriela.schubert/frontend" use a tag mais recente
images:
- name: frontend
  newName: gabrielaschubert/frontend
  newTag: 5b0d7baf213a6c33b9ae56684087ada3f67746ae
- name: gabrielaschubert/frontend
  newTag: latest
