apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Permite acesso externo
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 80
