# Nome do workflow
name: Build and Push Frontend Docker Image

# Quando o workflow será executado
on:
  push:
    branches:
      - main
      - feature/test-docker

jobs:
  build:
    runs-on: ubuntu-latest  # Máquina usada para rodar o job

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Clona o repositório

      - name: Login to DockerHub
        uses: docker/login-action@v3  # Autenticação no DockerHub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3  # Suporte a multiplataforma

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3  # Configura builder para imagens

      - name: Build and push Docker image
        uses: docker/build-push-action@v6  # Constrói e envia imagem Docker
        with:
          context: .
          push: true
          tags: |
            gabrielaschubert/frontend:latest
            gabrielaschubert/frontend:${{ github.sha }}

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v2  # Instala o Kustomize

      - name: Update kustomization.yaml
        run: |
          cd k8s
          kustomize edit set image frontend=gabrielaschubert/frontend:${GITHUB_SHA}  # Atualiza tag da imagem

      - name: Commit changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git commit -am "Update kustomization.yaml with new image" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master  # Envia as alterações para o repositório
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
